# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-02 19:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20161102_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 2, 19, 35, 50, 928927, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
